name: CI

on:
  
  push:
    branches:
      - dev
      - main
  
  pull_request:
    types: [closed]
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - run: echo "CI job running!"
