name: Semantic Versioning

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

jobs:
  tagging:
    if: github.event.pull_request.merged == true && github.head_ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "Tagging job running!"
