name: Semantic Versioning

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "Tagging job running!"
